included:
  - Sources
  - TartuWeatherProvider-iOSTests
excluded:
  - Pods

disabled_rules:
  - trailing_whitespace

reporter: "xcode"

identifier_name:
  excluded:
    - id
    - km
    - success(_:)
    - failure(_:)
