osx_image: xcode9
language: objective-c
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MeteoLVProvider.xcworkspace -scheme MeteoLVProvider-Example -destination 'platform=iOS Simulator,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty
- pod lib lint
