osx_image: xcode9.4
language: objective-c
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update
  - brew outdated swiftlint || brew upgrade swiftlint
  - gem install cocoapods --pre
script:
- ./build.sh
- swift build
- carthage build --no-skip-current
- pod repo update
- pod lib lint --verbose
