version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      - run:
          name: Carthage
          command: |
            brew update
            brew outdated carthage || brew upgrade carthage
            carthage update

      - run:
          name: Install Swiftlint
          command: brew install swiftlint

      - run:
          name: Test and build iOS
          command: set -o pipefail && xcodebuild -project MeteoLVProvider.xcodeproj -scheme MeteoLVProvider-iOS -destination 'platform=iOS Simulator,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty

      - run:
          name: SwiftPM Build
          command: swift build

      - run:
          name: Carthage Build
          command: carthage build --no-skip-current

      - run:
          name: Build tvOS
          command: set -o pipefail && xcodebuild -project MeteoLVProvider.xcodeproj -scheme MeteoLVProvider-tvOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty

      - run:
          name: Build watchOS
          command: set -o pipefail && xcodebuild -project MeteoLVProvider.xcodeproj -scheme MeteoLVProvider-watchOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty

      - run:
          name: Build macOS
          command: set -o pipefail && xcodebuild -project MeteoLVProvider.xcodeproj -scheme MeteoLVProvider-macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty

      - run:
          name: Update pods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      - run:
          name: Pod lib lint
          command: pod lib lint --allow-warnings

      - run:
          name: Codeconv
          command: |
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
