update_fastlane

default_platform :ios

platform :ios do
  desc "Depoy new Tartu Weather provider version"
  lane :release do
    ensure_git_branch
    version = version_get_podspec(path: "MeteoLVProvider.podspec")
    changelog = prompt(text: "Changelog: ", multi_line_end_keyword: "END")
    github_release = set_github_release(
      repository_name: "fassko/MeteoLVProvider",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
    push
  end

  desc "Pod push"
  lane :push do
    pod_push(
      allow_warnings: true,
      verbose: true,
      use_libraries: true
    )
  end

  desc "Cocoapod linter"
  lane :lint do
    pod_lib_lint(
      allow_warnings: true,
      verbose: true,
      use_libraries: true
    )
  end

end
