name: Build Swift API
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: macOS-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Install Swiftlint
        run: brew install swiftlint

      - name: Build iOS
        run: set -o pipefail && xcodebuild -project MeteoLVProvider.xcodeproj -scheme MeteoLVProvider -destination 'platform=iOS Simulator,name=iPhone 11 Pro' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty

      - name: SwiftPM Build
        run: swift build

      - name: Update ruby and cocoapods
        run: |
          sudo gem install cocoapods --no-doc
          sudo gem cleanup

      - name: Example project
        run: |
          cd Example
          pod update
          xcodebuild clean build -workspace MeteoLVProvider.xcworkspace -scheme MeteoLVProvider-Example CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

      - name: Pod lib lint
        run: pod lib lint --allow-warnings
